version: '3.0'
services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: db